### ISSUE TITLE
Bug Fixes

### ISSUE THREAD

**Issue by cloaked2222** [HW-PlayersPatch/Development#102]
[HWR Bug Thread](https://forums.gearboxsoftware.com/t/hwr-bugs-solutions/1639765/1)
Below I've listed things that can be fixed for build 10.

**Crates**
https://forums.gearboxsoftware.com/t/bug-bugs-in-crate-code/1526876
Per the thread I fixed ship crates for build 9, but research crates still need to be fixed. Not sure exactly whats wrong with them atm. Note: Try comparing v1.3 to 2.205 for crates.lua ChooseCrateRewardTech(iPlayer).

**Grav Fix**
Resources\Trebic's Grav Fix (So ships are no longer locked down after it moves away).zip
If we test this really well to ensure no syncs, we can use it in build 10.

**Comment by Echo1707** [comment]
Grav Fix: if you upload a test version on steam, you can test that with RoBeY :) (I whish I could, but timezones...)

**Comment by Novaras** [comment]
Closing this, make new issues if needed.
