### ISSUE TITLE
HW1 Research Costs for Build 10

### ISSUE THREAD

**Issue by cloaked2222** [HW-PlayersPatch/Development#132]
HW1 Research Costs need more work, lets get this right for build 10. Fear, let us know what you think is best here.

Research | Ship/Class | b7 Cost | b9 Cost | b10 Cost | b7 Base Time | b9 Base Time
-- | -- | -- | -- | -- | -- | --
kus_fighterdrive | kus_scout | 100 | 500 |   | 35 | 20
kus_fighterchassis | kus_interceptor | 200 | 800 |   | 50 | 30
kus_defendersubsystems | kus_defender | 400 | 1000 |   | 90 | 75
kus_cloakedfighter | kus_cloakedfighter | 500 | 1100 |   | 100 | 100
tai_defensefighter | tai_defensefighter | 500 | 1100 |   | 100 | 100
kus_corvettedrive | kus_lightcorvette | 800 | 1500 |   | 100 | 75
kus_corvettechassis | kus_salvagecorvette | 900 | 1200 |   | 90 | 60
kus_heavycorvetteupgrade | kus_heavycorvette | 600 | 600 |   | 20   (30 in 2.1) | 30
kus_fasttrackingturrets | kus_multiguncorvette | 700 | 800 |   | 25   (40 in 2.1) | 40
kus_minelayingtech | kus_minelayercorvette | 700 | 1200 |   | 70 | 100
kus_capitalshipdrive | kus_supportfrigate | 800 | 1300 |   | 100 | 75
kus_capitalshipchassis | kus_assaultfrigate | 1400 | 1500 |   | 120 | 90
kus_ioncannons | kus_ioncannonfrigate | 1000 | 2000 |   | 90 | 120
kus_dronetechnology | kus_dronefrigate | 1100 | 1300 |   | 40 | 80
tai_defensefield | tai_fieldfrigate | 1100 | 1300 |   | 40 | 80
kus_supercapitalshipdrive | kus_carrier | 1300 | 1700 |   | 100 | 50
kus_superheavychassis | kus_destroyer | 1900 | 5000 |   | 75 | 140
kus_guidedmissiles | kus_missiledestroyer | 1400 | 3500 |   | 60 | 100
kus_heavyguns | kus_heavycruiser | 5500 | 9000 |   | 360 | 360
kus_gravitygenerator | kus_gravwellgenerator | 500 | 500 |   | 50   (100 in 2.1) | 100
kus_cloakgenerator | kus_cloakgenerator | 800 | 800 |   | 100 | 100
kus_proximitysensor | kus_proximitysensor | 250 | 500 |   | 40 | 40
kus_sensorarray | kus_sensorarray | 350 | 1000 |   | 80 | 80
Kushan Total | | 21200 | 36800 | | 1795 | 1865

Here's where build 8/9 research costs were determined:
https://github.com/HW-PlayersPatch/2.3/tree/Build10/BalanceInfo/Core%20Comparison

**Comment by cloaked2222** [comment]
I tweaked your research cost buffs some to fit better with the overall design. Summary of b9->b10 cost changes by class:
Research | Fear Cost Change | Clo Cost Change
-- | -- | --
Fighters | -1050 | -1100
Corvettes | -1400 | -1500
Frigates | -1100 | -1100
Capitals | -7000 | -5500
Non-Combat | -950 | -800
Total | -11500 | -10000

Research | Ship/Class | b7 Cost | b9 Cost | Fear Cost | **Clo** Cost | b7 Base Time | b9 Base Time
-- | -- | -- | -- | -- | -- | -- | --
kus_fighterdrive | kus_scout | 100 | 500 | 100 | **200** | 35 | 20
kus_fighterchassis | kus_interceptor | 200 | 800 | 500 | **300** | 50 | 30
kus_defendersubsystems | kus_defender | 400 | 1000 | 750 | **800** | 90 | 75
kus_cloakedfighter | kus_cloakedfighter | 500 | 1100 | 1000 | **1000** | 100 | 100
tai_defensefighter | tai_defensefighter | 500 | 1100 | 1000 | **1000** | 100 | 100
kus_corvettedrive | kus_lightcorvette | 800 | 1500 | 800 | **1000** | 100 | 75
kus_corvettechassis | kus_salvagecorvette | 900 | 1200 | 500 | **700** | 90 | 60
kus_heavycorvetteupgrade | kus_heavycorvette | 600 | 600 | 800 | **400** | 20   (30 in 2.1) | 30
kus_fasttrackingturrets | kus_multiguncorvette | 700 | 800 | 800 | **500** | 25   (40 in 2.1) | 40
kus_minelayingtech | kus_minelayercorvette | 700 | 1200 | 1000 | **1200** | 70 | 100
kus_capitalshipdrive | kus_supportfrigate | 800 | 1300 | 800 | **1000** | 100 | 75
kus_capitalshipchassis | kus_assaultfrigate | 1400 | 1500 | 1200 | **1200** | 120 | 90
kus_ioncannons | kus_ioncannonfrigate | 1000 | 2000 | 2000 | **1700** | 90 | 120
kus_dronetechnology | kus_dronefrigate | 1100 | 1300 | 1000 | **1100** | 40 | 80
tai_defensefield | tai_fieldfrigate | 1100 | 1300 | 1300 | **1100** | 40 | 80
kus_supercapitalshipdrive | kus_carrier | 1300 | 1700 | 1700 | **1700** | 100 | 50
kus_superheavychassis | kus_destroyer | 1900 | 5000 | 2500 | **3000** | 75 | 140
kus_guidedmissiles | kus_missiledestroyer | 1400 | 3500 | 2500 | **2000** | 60 | 100
kus_heavyguns | kus_heavycruiser | 5500 | 9000 | 5500 | **7000** | 360 | 360
kus_gravitygenerator | kus_gravwellgenerator | 500 | 500 | 500 | **500** | 50   (100 in 2.1) | 100
kus_cloakgenerator | kus_cloakgenerator | 800 | 800 | 500 | **500** | 100 | 100
kus_proximitysensor | kus_proximitysensor | 250 | 500 | 350 | **500** | 40 | 40
kus_sensorarray | kus_sensorarray | 350 | 1000 | 500 | **500** | 80 | 80
Kushan   Total |   | 21200 | 36800 | 25300 | **26800** | 1795 | 1865

Lets just try costs first. I've now included b7 times here, but keep in mind these are base times with no research ships (Base=1.0, 1xResearch Ship=0.71, 2xResearchShip=0.58, 3xResearchship=0.50).

I updated the "2.3 Test" patch and made it public. Get some games in!
https://steamcommunity.com/sharedfiles/filedetails/?id=1413859511

**Comment by Novaras** [comment]
i dont like salvage tech being costly as its *usually* just a dead tech

thats why i made it pretty cheap and redistributed to combat vettes

**Comment by Novaras** [comment]
Is there no way to have multiplayer tech to be different from singleplayer? If it were doable I'd immediately flatten some of the hw1 tree as the main balance nightmare is trying to buff units up the tree without affecting the units above and below

**Comment by Novaras** [comment]
I'm closing this @cloaked2222 , feel free to open back up if you think its still relevant.
