### ISSUE TITLE
MP: HW2 Upgrade Percents

### ISSUE THREAD

**Issue by cloaked2222** [HW-PlayersPatch/Development#143]
-Vay scout base speed 2.3=420, 2.4=350. This is silly slow making the vay scout useless the first few minutes of the game, and your vay probes will get pffted (as you saw me pfft dozens of S's probes in our games). Perhaps grant the vay scout a 1.2x speed upgrade by default so it starts at 420 again. but still maxes at like 512 per 2.4.

-So you know how vay scouts start silly slow? Well that's just the tip of the iceberg, the problem is deeper than that. 
In SC2 upgrades typically give small increments. Marine attack upgrades lv1/2/3 is 17%/33%/50% (6->7->8->9 damage).
In hw2c all corv/frig/capital hull upgrades lv1/2 is 30%/60%. Speed upgrades lv1/2 is 20%/35% (fighters are 25%/50%).
For hwr2.0, gbx raised the base health/speed then made hull lv1 40% and speed lv1 25% (fighters are 40%). This is too much of a leap, as is lv0 units are so weak its somewhat silly to send them into battle. As is upgrades are semi mandatory before any fight, when upgrades should simply make a good thing better. This was a bad move that happened in May 2015, just before I joined the balance team... This guy is the reason why gbx did this, they just listened bad advice: https://forums.gearboxsoftware.com/t/lets-talk-hw2-2-tier-upgrade-system-and-how-it-often-does-nothing-and-is-actually-useless-fluff/187852/1

Not for this next build, but perhaps the build after I propose lowering the lv1 upgrade percent's to what they were in hw2c (make most speed upgrades 15%, 25% for fighters), then just increase base health/speed so the fully upgraded stats are the same.

**Comment by Novaras** [comment]
Should be okay. Would you make upgrades more expensive then?

Also, any consideration for a 0->1->2 tier upgrade system like classic had? I think that could cause big headaches for hw1 but yeah.

**Comment by cloaked2222** [comment]
While I feel this is a good idea. Its not mandatory, would take significant effort, and would be a pretty big change from v2.1. HW3 is just 3 years off. I'll pass.
