### ISSUE TITLE
MP: Drone Frigates

### ISSUE THREAD

**Issue by cloaked2222** [HW-PlayersPatch/Development#144]
In 2.1, drones look pretty but rarely attack when the ship is attack moving. In 2.4 Fear made some changes to fix the balance (yay), but it looks like its yanking a pack of dogs back every few seconds. -_-
https://www.youtube.com/watch?v=ed2bS7EINp4&feature=youtu.be

The look of the hw1c drones in a circle around the frig is quite important. This needs work, I think Fear's kinda thrown in the towel for now so I'll try to work on it sometime.

Edit: Fear said to make each drone move to their original parade location around the ship, rather than just towards the rear of the ship. See kus_dronefrigate_parade.lua for the coordinates.

**Comment by Novaras** [comment]
why?

**Comment by Novaras** [comment]
The current behavior is fine but could definitely use tweaking to make it look better.

You're just gonna have to give up on the sphere for a move attacking drone frigate. Formations, guarding, nor parading will work.

Only 'soft' move commands allow move-fire behavior. 'Hard' move commands such as parade will override any attack order currently issued.

Currently the drones are simply told to move to where the frigate is located if they are too far from it. This could be improved quickly in various ways:
- tweaking the distance
- tweaking the ms of drones
- adding randomness to the location the drones are 'yanked' to
- periodically issue a parade command just to get the sphere shape back a bit (will cause uncontrollable downtime on firing from drone frigates)

Drones will mostly keep the sphere for a stationary frigate too.

**Comment by Novaras** [comment]
I don't recall - any changes happened here?

**Comment by cloaked2222** [comment]
Ya please work on this some more. I even noted in the b10 change log that we're still working to improve this. (you are =P)

At a minimum: "Fear said to make each drone move to their original parade location around the ship, rather than just towards the rear of the ship. See kus_dronefrigate_parade.lua for the coordinates."

**Comment by Novaras** [comment]
https://github.com/HW-PlayersPatch/Development/pull/175

**Comment by Novaras** [comment]
merged to b11: https://github.com/HW-PlayersPatch/Development/commit/a5ac36dea1ad8e0963d72882e93003dafa2c5d5a

**Comment by cloaked2222** [comment]
2.3b9 tests:
Drone frig tests done while not moving.
4 flak vs 70 h int = 86sec (3+ test avg)
4 v ass vs 70 h int = 107
4 drone vs 70 h int = 109
4 flak vs 70 k int = 95sec (3+ test avg)
4 v ass vs 70 k int = 133
4 drone vs 70 k int = 120

2.3b10 tests:
4 drones vs 70 h int=50 (3+ test avg) **(target 85+)**
4 drones vs 70 k int=75 (3+ test avg) **(target 95+)**
4 flak vs 10 k lights = 137
4 drones vs 10 k lights = 99 **(target 120?)**
4 v ass vs 10 k lights = 78
4 k ass vs 10 k lights = 64

Drones are OP atm, suggested targets in bold.

**Comment by Novaras** [comment]
why flak -> drone?

**Comment by cloaked2222** [comment]
This has been the concept since 2016:
Vs fighter model is flak->drone->..v ass->........k ass.
Vs corv model is k ass->..v ass->......drone->flak
Flak is best vs fighters, and worst vs corvs. Drones are very similar but a bit more rounded (so a tad better vs corvs, and a tad worse vs fighters).

Performance is real:
![image](https://user-images.githubusercontent.com/18016573/65214020-53e4a400-da76-11e9-81e2-ca1c51563699.png)
I'm fine using the 2.1 damage/firedelay, but we could do damage 20 and firedelay 0.04 due to the above comment.

**Comment by Novaras** [comment]
already agree

# Drones
> *desc*
* **Weapons:**
  * **Kinetic gun:**
    * **Delay between shots:** `0.2 => 0.4` (+100%)
    * **Base damage:** `10 => 20` (+100%)

**Comment by cloaked2222** [comment]
Resolved

**Comment by cloaked2222** [comment]
A few more things to fix on the new drone script:
1. When the drones start attacking, they first all move/swap to a different position in the parade. lol Maybe the code is accidentally mixing up drone 0-13 with 1-14 somewhere, idk.

2. When you recall the drones, a couple often get stuck underneath the frig until you move it. Compare 2.1 lua recall code to current.

3. The sphere lags behind the frig. Try to keep it closer if possible, not a big deal if you can't. (this is a bit better than v2.1 tho I think).

**Comment by cloaked2222** [comment]
2ed22296be337736c7a977b76c0672cca0951780

Everything is now fixed, except the "drone shuffle" issue. When the drones start attacking, they first all move/swap to a different position in the parade. The problem is parade_positions is static, and doesn't rotate to match the direction the frig is facing. If your frig happens to be facing the default direction (after spawning via gbx balance test window), there's no shuffle.
