### ISSUE TITLE
Feature: Show Base Production Time

### ISSUE THREAD

**Issue by cloaked2222** [HW-PlayersPatch/Development#146]
Feature to show base production times for ships and research in the UI. This also shows research multiplier values (such as health increase %). This information is included in the build/research item description popup.

Production times could also be included in the item's title as a 2nd dropdown option. However then the production times would be shown twice in the popup (via the title and description). Additionally, the title only has room to state '60s'. This can be quite misleading if you have improved manufacturing researched, as ships will build much quicker than the time displayed (about 45s).

**Comment by cloaked2222** [comment]
Implemented. English only as LUA can't read UTF8 or whatever, only the exe can. If we ever localize the mod, they could be added to the local files. No option to turn on/off, just always on.

**Comment by Novaras** [comment]
Are those chatacters okay? Honesly my knowledge of string encoding is almost 0 so I have no idea why or what is really happening with it.

**Comment by cloaked2222** [comment]
I don't know if some of the characters in the screenshot are messed up or not, or if they would display properly on a machine w/ french installed. No clue.

Gonna close this. Like you said, if someone asks for it, we'll pursue further. Spent enough effort here already.
