### ISSUE TITLE
MP: Hgn EMP

### ISSUE THREAD

**Issue by cloaked2222** [HW-PlayersPatch/Development#154]
Make Hgn EMP penetration vs frigates 2x, Since Hgn misses fighters, this will make it much better vs frigates. (already good vs corvs now).

**Comment by Novaras** [comment]
Hw2 vettes have `75` emp shield - it will take 2 scouts to stun a single squad. As corvettes don't bunch up like fighters, I would **much** prefer it if they could oneshot vettes.
Frigates have `310` shield HP, meaning you currently need 15 scouts or 5 squads to stun a frigate.

I suggest:
* **EMP:**
  * **Base damage:** `20 => 30` (+50%)
  * **Damage multipliers:**
    * **vs Frigates:** `1.0 => 2.0` (+100%)

Now it takes three hits (one squad) to stun a vette, and 5 hits (2 squads) to stun a frigate.

Keep in mind EMP is
- expensive tech
- takes ints off the field
- has a cooldown

And these units (vettes, frigates), are nowhere near as vulnerable to being group stunned as fighters. Especially frigates. In fact, it may be worth reducing the cooldown to compensate, but I'll take a damage buff for now.

**Comment by cloaked2222** [comment]
In build 10:
HW2 ints/corvs take 2 hgn/vay EMP squads.
HW1 ints/corvs take 1 hgn/vay EMP squad.
Frigs take 4 or 5 hgn/vay EMP squads.

Since Hiig EMP misses fighters, just make it only take 2-3 squads to EMP frigs.

I do not wish to make either vay or hiig any better than they already are vs corvettes.

**Comment by Novaras** [comment]
What's the issue with strong hgn emp against vettes? I don't mind leaving it at two but the efficiency of EMP against non-fighters is totally massive due to no grouping.

**Comment by Novaras** [comment]
https://github.com/HW-PlayersPatch/Development/pull/193

**Comment by cloaked2222** [comment]
Since that attempted failed, u got any other ideas?

Perhaps we just have it so vay is good vs fighters/corvs/frigs and hiig is good vs corvs/frigs.

**Comment by Novaras** [comment]
Vgr is fine, with the changes in the other issue they'll also be fine.

So it's just Hgn, so let's have it 2 for vettes and 3 for frigates, or, pehaps, 2 for frigates?

I really prefer the idea of vay hitting fighters and vettes, and hgn hitting vettes and frigates.

Vgr:
Fighter: 4
Corvette: 6 <- this puts them in the same band as fighters, but the hit will need to be much cleaner from the scouts
Frigate: 10

--

Hgn:
Fighter: cant hit / 8
Corvette: 4
Frigate: 7 / also 4

---

Overall i think we just have to remember there *is* a big difference between stunning with 4 and stunning with 6 - emp shields regen very fast and a half second stagger can blow it. HWRM units also have pretty terrible pathing, and the scouts can be quite anal about when they think they can shoot their EMP

**Comment by cloaked2222** [comment]
The problem is how to do this as weapon penetration multipliers don't affect EMP, and all ships have the same EMP shields. So you can't just make hiig emp way better than vay emp vs frigs.

Thankfully I've finagled a solution to make vay take 4 squads vs frigs, while hiig only takes 3 squads vs frigs! I updated #195 to give vay emp 34 damage instead of 35.
Hiig currently often misses fighters due to deploying the bombs further away and other hiig emp weapon stats being different from vay, so no changes are needed vs fighters.
I'd like to keep them the same vs vettes.

In summary:
Vay: Good vs fighters/corvs (not as good vs frigs)
Hiig: Good vs corvs/frigs (not as good vs fighters)

**Comment by Novaras** [comment]
Yeah, that sounds really nice, good spot

**Comment by cloaked2222** [comment]
Solved with 195
