### ISSUE TITLE
MP: Hiig Hyperspace Times

### ISSUE THREAD

**Issue by cloaked2222** [HW-PlayersPatch/Development#155]
Build 10 made all hiig ships 6sec, except Hiig MS is 9.5 sec. Yesterday I made Hiig CC/SY 9.5 sec too to align the build ships.

Unfortunately the time just changes when you can give the ship orders. It does not speed up the HS animation. So now most hiig ships are out of sync. Find a way to speed up HS animation, or just revert all hiig ships to 9.5 sec.

The idea is cool. But its also not something anyone coming from 2.1 would expect, so its another learning curve.

**Comment by cloaked2222** [comment]
Implimented

**Comment by Novaras** [comment]
https://discordapp.com/channels/580754340973903882/580754340973903884/625083051772477450

not a bug before 2.3, think a number was missed in migration, I'd like to keep it low

**Comment by cloaked2222** [comment]
657b5e7bfd355daca2bea7344412a2a24c554a56
