### ISSUE TITLE
Vgr Hyperspace Gates (vision)

### ISSUE THREAD

**Issue by Novaras** [HW-PlayersPatch/Development#158]
Current stats for hs gate vision are way out of line:

2.3b9 => {2.4b11}/2.3b10
* **Vision:**
  * **Vision range:** `1000 => 4000` (+300%)
  * **Primary sensors range:** `4000 => 7500` (+87.5%)
  * **Secondary sensors range:** `4000 => 7500` (+87.5%)

These can all be halved or just reverted imo.

Hyperspace gates can also be jumped. Is this okay?

**Comment by cloaked2222** [comment]
Hyper gate jumping is awesume IMHO. Honestly even with 10+ other buffs I never even bothered with them, until they could jump. Once they're linked, they can no longer jump or move. Think of jumping as really fast movement speed.

I don't care about vision. The other two vay plats have 1/4/5. Do the same or a little better for this plat.

**Comment by Novaras** [comment]
I'll match other plats.

**Comment by Novaras** [comment]
https://github.com/HW-PlayersPatch/Development/pull/174
