### ISSUE TITLE
Taiidan Field Frigates

### ISSUE THREAD

**Issue by cloaked2222** [HW-PlayersPatch/Development#164]
Hiig Defense Field Frigates block most stuff pretty good while on. All weapons are configured with an appropriate SheildPenetration value. This allows BC/DD weapons to go through the field more often, than frig weapons.

**Effectiveness**
Taii Field Frigates are always on, they block 85% of bullets, and when you stack two they block 98% of bullets.

**Fighters/Frigs**
Per hw1c, they are supposed to protect frigs/capital ships from strikecraft. In the past they were tested and balanced decently vs strikecraft, as once strikecraft get inside the field they can do some damage to the frig. Currently they hard counter HW1/Vay assault frigates rendering them MOL useless. Edit: This is fine, as it was the same in hw1c.

**Capitals**
Taii FF's were never really tested vs capitals. MagneticFieldPenetration is currently only setup on Hiig DD guns, and the vay BC trinity. So 2 Field Frigates block 98% of nearly all BC/DD bullets! This is extremely powerful in capital balls. Here's how useful the FF is vs capitals right now, based on how much of their firepower is from their bullets:
Hiig DDs: Useless (MagneticFieldPenetration is set)
Vay DDs: Meh (it has a gun but most damage is from missiles)
HW1 DDs: Decent
Hiig BCs: Decent
Vay BCs: Useless (MagneticFieldPenetration is set)
HW1 HCs: Decent
While not everyone realizes it, in a big battle the Taii FF is as important as a target as the Hiig DFF.

**Comment by Novaras** [comment]
What? It's totally reflective of classic lol. Fields are even stronger in classic compared to rm in fact. Assaults are just as ruined in classic as they are in rm by fields - this is well known and is actually fine as ions hard counter fields and beat assaults somewhat.

You can only make two of them, the shields are small, the tech is expensive, the unit has no firepower, and doesn't do anything at all against the things which naturally beat assault frigates (ions, DDs). This is not a broken unit.

**Comment by Novaras** [comment]
What do you want done, just the stuff re; capital-class bullets?

**Comment by cloaked2222** [comment]
First a specific Q: In hw1c did 2 Field Frigates shut down 98% of bullets from 10+ assault frigates like what we have in HWR?

We need to setup MagneticFieldPenetration on all frigate+ weapons to reflect hw1c. Definitely capitals, and frigs if needed.

**Comment by Novaras** [comment]
Ffs: https://discordapp.com/channels/128196211969753088/248114648090542080/562538863889874954

Dfs: https://discordapp.com/channels/128196211969753088/248114648090542080/562544776541372417

**Comment by cloaked2222** [comment]
Where are you getting the "Ffs" and "Dfs" acronyms from? I'm confused everytime I see them, lol.
Tai Defense Fighters are usually "DF"
Tai Defense Field Frigates are usually "DFF" or "FF".

So in hw1c one Field Frigate actually blocked 93% of all bullets from any ship?

With that knowledge, what do you think we should do if anything regarding MagneticFieldPenetration capitals?

**Comment by Novaras** [comment]
Def frig:
- Hgn DD: no effect
- Hgn BC: bullets
- Vay DD: bullets
- Vay BC: bullets
- HW1 DD: bullets
- HW1 HC: bullets

Overall the only interesting thing is its matchup with HW1 HC, as most of their damage is coming from the bullets.

**Comment by cloaked2222** [comment]
![image](https://user-images.githubusercontent.com/18016573/70847322-5e25fc80-1e31-11ea-9bdc-318e89943b01.png)
