### ISSUE TITLE
Drone Frigate Drones give combat reports 

### ISSUE THREAD

**Issue by Gunnerth** [HW-PlayersPatch/Development#173]
Drone frigate drones will provide combat reports every time they enter combat. They report moving while engaging, and engaging targets. Combat reports seem to be the only lines they'll trigger. 
I believe the speech logic thinks they're fighters and has them respond as fighters

**Comment by Novaras** [comment]
Cool, how long will this take to fix? Sounds like a quick one?

If it's gonna be simple stuff I'll throw it into the b11 milestone.

**Comment by cloaked2222** [comment]
https://github.com/HW-PlayersPatch/Development/pull/253
