### ISSUE TITLE
HW1 Campaign Default ROE for your ships

### ISSUE THREAD

**Issue by Novaras** [HW-PlayersPatch/Development#176]
Default ROE for your ships when you begin a mission in HW1RM campaign is passive. I guess this was to emulate the behavior of ships in hw1c where they would fire back on attackers but not persue them unless ordered to.

This is totally garbage in remastered - should be set to neutral ROE.

**Comment by Novaras** [comment]
I'm down to just put offensive on everything, I'll do a playthrough to check it out.

**Comment by cloaked2222** [comment]
Its neutral ROE for the hw2 campaign right? Prolly just need to compare the hw1 vs hw2 campaign files in the file share, to figure out what controls this.

**Comment by cloaked2222** [comment]
dacd77085fd2b0b8ed2c6929adb57e4e890d02e1
