### ISSUE TITLE
HW2 Bomber Extra Weapon Changes

### ISSUE THREAD

**Issue by cloaked2222** [HW-PlayersPatch/Development#187]
Apply pen/accuracy changes in hgn_antishipbomblauncher.wepn to hgn_bomblauncher.wepn.

Same for vgr_antishipbomblauncher.wepn to vgr_bomblauncher.wepn.

This was an oversight from older builds.

See Stats Tool 2.3b10to2.1.

**Comment by Novaras** [comment]
Will do this evening

**Comment by Novaras** [comment]
https://github.com/HW-PlayersPatch/Development/pull/188

**Comment by cloaked2222** [comment]
e271b9d861167b51596d25ebaef69bef4fc35bd9
