### ISSUE TITLE
EMP Friendly Fire and vs Frigs

### ISSUE THREAD

**Issue by cloaked2222** [HW-PlayersPatch/Development#195]
### hw2c
EMP Damage: 35 / 105 (per scout/squad)
EMP Shields:
Scouts 0 (1 scout)
Fighters/Corvs 75 (3 scouts)
Frigs 310 (9 scouts)
Friendly Fire 0%

### Current State
EMP Damage: 20 / 60 (per scout/squad)
EMP Shields:
Scouts 100 (5 scouts)
hw2 Fighters/Corvs 75 (4 scouts)
hw1 Fighters 30 (2 scouts)
hw1 Corvs 45 (3 scouts)
Frigs 310 (16 scouts...)
Friendly Fire 50% (When 4 scout squads try to emp the same target, they emp each other...)

### Suggested Changes
Hiig EMP Damage: 35 / 105 (per scout/squad)
Vay EMP Damage: 34 / 102 (per scout/squad)
EMP Shields:
Scouts 200 (6 scouts)
hw2 Fighters/Corvs 110 (4 scouts)
hw1 Fighters 65 (2 scouts)
hw1 Corvs 65 (2 scouts)
Frigs 310 (9 scouts, 10 for vaygr so it takes an extra squad)
Friendly Fire 45% (When 5 scout squads try to emp the same target, they emp each other.)

**Comment by Novaras** [comment]
Fine, keep it at 5 scouts for self-stunning, everything else looks good.

Is this for Hgn only?

**Comment by cloaked2222** [comment]
The above changes would need to be universal across all races.

**Comment by Novaras** [comment]
you want to make emp identical again?

**Comment by cloaked2222** [comment]
This should have been done years ago. The current state of EMP was done by me for v2.0 as a quick 'band aid' to fix the introduction of friendly fire which originally resulting in scouts emping themselves every time, rofl.

This is a separate issue from making hiig emp useful / different from vay. Lets do the above, then continue brainstorming hiig here https://github.com/HW-PlayersPatch/Development/issues/154

**Comment by Novaras** [comment]
Ah sorry, sounds totally reasonable then.

**Comment by cloaked2222** [comment]
Suggested changes all implemented: 371fb4b1d9dcc795a3d5f0c1e7712665a65a85c4
