### ISSUE TITLE
HW1 Bomber Weapons

### ISSUE THREAD

**Issue by cloaked2222** [HW-PlayersPatch/Development#202]
2.3 b10 vs 2.1:
![image](https://user-images.githubusercontent.com/18016573/65353799-040ff500-dbbc-11e9-8a76-d5ab68f73c83.png)
(note the other hiig/vay weapons have been updated to match the shipbomblauncher. The subsystemlaunchers do bonus damage vs subs)

A. 2.4 changed the subsystem pen, frigate acc, and capital acc. I'd just undo to align with hiig/vay.

B. Sometime during 2.3 b1-b9 I made HW1 bombers about 35% better vs frig, capital, and resource armor than hw2 bombers. No idea why. Perhaps this needs to go down? Seems like hw1 bombers do melt frigs. Thoughts?

**Comment by Novaras** [comment]
Do they really? Always feel like hw2 bombers hit harder. Formation bonuses perhaps?

Don't think this is a critical issue.

**Comment by cloaked2222** [comment]
I tested, turns out "B" is needed to make HW1 bombers as good as Hiig bombers (upgraded) vs frigs.
