### ISSUE TITLE
Trinity Cannon SFX

### ISSUE THREAD

**Issue by cloaked2222** [HW-PlayersPatch/Development#213]
Making an issue for this so it doesn't get lost in the discord chat.

Here's what needs to be done:
![image](https://user-images.githubusercontent.com/18016573/65395425-889f7680-dd68-11e9-9601-253953aef2a4.png)

**Comment by Novaras** [comment]
Not throwing into b11?

**Comment by Gunnerth** [comment]
[VBC Sounds.zip](https://github.com/HW-PlayersPatch/Development/files/3649419/VBC.Sounds.zip)

Here's the current sounds at 1 second

**Comment by cloaked2222** [comment]
Thanks Gunnerth! Lets use "Beef HW2 sound only.aifr". The zap sounded foreign compared to the other Homeworld franchise sound effects.

Can you recommend a player for that file type? I just have Audacity.

If a pull is ready this week I might include it in b11. Otherwise no rush and b12 is fine.

**Comment by Gunnerth** [comment]
rename them to FDA and they can be used in game. These are the beef sounds as posted on discord
[VBC Sounds.zip](https://github.com/HW-PlayersPatch/Development/files/3650469/VBC.Sounds.zip)

**Comment by Novaras** [comment]
-_-

**Comment by cloaked2222** [comment]
https://github.com/HW-PlayersPatch/Development/pull/184
