### ISSUE TITLE
HW1 Scout Speed Burst

### ISSUE THREAD

**Issue by cloaked2222** [HW-PlayersPatch/Development#216]
In hw1c it lasted about 8 seconds, and took about 8-9 seconds to fully recharge the energy. You could stop/start the ability whenever as long as you had a little bit of energy. Currently it lasts 30seconds, takes 2min to recharge and you can only turn it on when u have max energy (can stop anytime below like 85% energy).

The issue is hw1 can press speed boost once and usually save their scout.

Reference:
Ints=488
Hiig Scout=480
Vay Scout=490

Current:
Boost value=10%
Boost duration=30sec
Boost recharge=120sec
Base speed=460
Boost speed=506

Proposal:
Boost value=10%
Boost duration=10sec
Boost recharge=40sec
Base speed=460
Boost speed=506
Reduce the duration/recharge by 1/3. Enable stop/starting the ability whenever as long as you have a little bit of energy.

Implementation:
Old: addAbility(NewShipType,"CustomCommand",1,"Speed Burst",1,0,1200,200,4,1,0
New: addAbility(NewShipType,"CustomCommand",1,"Speed Burst",1,0,1200,120,12,3,1100

**Comment by Novaras** [comment]
What is trying to be solved here

**Comment by cloaked2222** [comment]
A. Making speed burst closer to hw1c.
B. Currently clicking speed burst once is basically a get out of jail card and your cheap hw1 scout wont die. IE: Free vision. This change will require micro/focus and make your average hw1 scout escape speed close to hiig scout's speed. Can be considered a Nerf to the cheap hw1 scouts which cost 1/3rd as much as hw2 scouts at 300ru.

**Comment by Novaras** [comment]
12/10/10 for me, speed boosting and being slower than ints is pretty odd imo?

**Comment by Novaras** [comment]
I don't see this as a pressing issue, let's throw it into Build12 instead.

**Comment by cloaked2222** [comment]
Edited the OP for clarity. Give a +1 if this looks good Fear.

**Comment by Novaras** [comment]
Well okay, but would like to regain that anytime toggling. Rn it's pretty weird to use

**Comment by cloaked2222** [comment]
108fa87b1cc6add68a36eaa5630455391ff37e3a
