### ISSUE TITLE
Recoil on Turret Subsystems

### ISSUE THREAD

**Issue by cloaked2222** [HW-PlayersPatch/Development#228]
"Chosen One: When u guys will fix Hiigaran Gunships vettes barrel recoil? IIRC it was in original game and in some version, but it do not apear in mod."

**Comment by Novaras** [comment]
I guess it's to do with the fact that gunships don't have their weapon on a hardpoint?

Art actually did find something out which relates to this: https://github.com/HW-PlayersPatch/Development/issues/234

**Comment by Stuart1998** [comment]
Recoil is broken for all subsystem weapons it seems. Might need to undo Gearbox's moving turreted weapons onto subsystems to fix it - can't imagine that will be a simple process.
