### ISSUE TITLE
Dreadnought Weapon Beam Effect

### ISSUE THREAD

**Issue by cloaked2222** [HW-PlayersPatch/Development#229]
"SQUID N TROLL OCTOPUS Homeworld 2 Dreadnought does not do any damage with his Phase cannon. It will show the animations, but you do not see the beam and it doesn't do any damage at all. At least, this is the case on mission 13."

The dreadnaught works fine in M11,12,14,15, and when spawned on any map (same for sajuuk). But on M13 the dreadnaught beam does not appear, even if you spawn a 2nd one with the balance window. Tested in v2.1 and v2.3. This bug was not present in v1.3. This v2.1 bug needs fixing.

Note: hgn_dreadnaughtioncannon.wepn If you swap Super_Beam for IonBeam_bc (from a Hiig BC), then the Hiig BC effect works. So it may be something with the Super_Beam in Mission 13.

**Comment by Stuart1998** [comment]
Pretty sure this is only a visual issue and damage is still dealt regardless.

**Comment by cloaked2222** [comment]
Ya I think so too, you can see the hit effects on the target ship. Just no beam effect.

**Comment by cloaked2222** [comment]
In m13_balcora_gate.lua comment out lines to fix the beam:
1205 Rule_Remove ("Rule_gateAttackSetup")
1248 FX_StopEffect( Chunk2Beam )
1267 FX_StopEffect( Chunk3Beam )

Took many hours of trail and error to get this fixed....

618cc2909037163ba4431861314f820cd8b3426b
