### ISSUE TITLE
Sensor distortion inconsistency

### ISSUE THREAD

**Issue by Novaras** [HW-PlayersPatch/Development#234]
https://discordapp.com/channels/128196211969753088/500389732954537984/628741535663652864

Can someone pls take 10m to confirm?

**Comment by cloaked2222** [comment]
Looks pretty confirmed.

Not sure if its possible to undo weapon subs, and simply undoing 2.0 changes may have other negative consequences. GBX made weapon subsystems for a reason, don't recall off hand the benefits tho. Maybe partially to do with pass through damage and collision meshes, but I'm sure there was more in play.
