### ISSUE TITLE
Specialty Units Retaliation Range

### ISSUE THREAD

**Issue by cloaked2222** [HW-PlayersPatch/Development#237]
Regarding this concern: https://steamcommunity.com/workshop/filedetails/discussion/1190476337/1848072002757085620/#c1629665087672163701

HWR has three Rules of Engagement (ROE) that match hw2c, but differ from hw1c:
Offensive moves to engage enemies in range.
Defensive moves to engage enemies in range only if they are attacking friendly ships nearby.
Passive doesn't move or fire weapons on its own.

hw1c's Neutral was like a "Hold Position" - ships strafed near their parade location while firing their weapons. Unfortunately HWR does not a ROE like that. Obviously it would be great if hw1c's Nuetral ROE existed, but thats not possible afaik. In HWR all ships built default to Defensive ROE. Its up to the player to select the ROE for the situation, and to control their units properly after they are built.

However perhaps some ships such as repair corvettes and support frigates should default to Passive? This would prevent them from running into battle, which would be great. But also means they will sit there doing nothing when being attacked, rather than attacking back or moving to dodge enemy weapons. A moving repair corvette is hard to kill, but if its just sitting there its easy to pick off.

Pros/Cons/Thoughts?

Would need to review all ships and determine if any others should go Passive too like salvage corvettes.

**Comment by Novaras** [comment]
I'd prefer if they just kept the current behavior, I think if we do this people are just gonna be upset in the reverse direction ('why are my rep vettes just sitting and dying! why are my support frigates always sitting at home while my army goes off to fight!!!!11;)

**Comment by RoBeY4Gate** [comment]
While I would prefer passive I will have to agree with fear.

**Comment by cloaked2222** [comment]
For most combat ships its OK if they just throw themselves into combat. But for repair ships, you have to give them repair targets to be effective. When repair corvettes/support frigates/salvage corvettes dive into battle on their own, they're rather useless cannon-fodder. Just think how dumb it would be if after you built probes, they moved into a battle on their own.

Its much easier for the player, if they just stay in parade formation. Then you can select them and give them a proper repair/salvage target. If you want them to move closer to a battle after being built, you simply setup a rally location for your production ship. Passive does have the downside of just sitting idle when being attacked however...

Luckily I just thought of a better solution! These units can keep their default Defensive tactics, we just need to lower their retaliation ranges. They shouldn't run off when a battle is happening in the distance, but they definitely should move if being attacked.

**Comment by Novaras** [comment]
Sounds perfect.

**Comment by Novaras** [comment]
https://github.com/HW-PlayersPatch/Development/pull/241

**Comment by cloaked2222** [comment]
4800->3600 isn't much of an improvement, they still run off too easily. I did some testing and 2k seems to be about right: 
![image](https://user-images.githubusercontent.com/18016573/67613154-45c22b80-f778-11e9-9043-adaf391d252c.png)

Regarding other specialty ships:
Salvage corvettes and taiidan field frigates can't attack and just sit still.
HW1 and HW2 Minelayer corvettes can't auto-attack, but still try to do attack runs... (#242)
Hiig defense field frigates attack.
Marine/Infiltrator frigates attack.
Other specialty units seem fine.

Lets set the retaliation range to 2k on all the named ships above. These units are mainly useful when you give them their specialty command. They are basically cannon fodder when they run off into battle and start firing their weapons which are about as effective as a scout attacking, lol.

**Comment by cloaked2222** [comment]
c645e01961722e86200a500e7ea895b72237a6f1
