### ISSUE TITLE
Missile Volley

### ISSUE THREAD

**Issue by cloaked2222** [HW-PlayersPatch/Development#254]
In HWR the missile destroyer's normal attack fires missiles constantly. The missile volley ability has a cooldown of 50 seconds per v2.1, before it can be used again. The missile volley ability doesn't stop the unit from continuing its normal attack.

In hw1c  the missile destroyer builds missiles slower than it can fire them. When it first enters combat it fires its full inventory somewhat rapidly, then slows down to the missile build time. The missile volley ability simply dumps the current missile inventory all at once. So for example you might have an inventory of 32 missiles, or just 8 missiles. After using the ability, the ship is idle for about 70 seconds while it builds about 8 missiles. Then it starts firing normally again. The missile volley ability isn't really useful again, unless you pull the ship from combat to allow it to build up a large missile inventory again. So after you use the ability for the first time, you'd need to pull it from combat for say 120 seconds before the ability is really useful again.

I feel the cooldown is just too quick atm. I'd propose changing the HWR Missile Burst cooldown to somewhere between 70 and 120 seconds closer to hw1c. 70 is prolly fine for HWR, I'd consider this a minor balance change. Thoughts?

**Comment by Novaras** [comment]
whats the purpose of this change? volley is pretty inline right now

**Comment by cloaked2222** [comment]
I made it 50->70 seconds like we talked about back in Jan f00cd5d9900b47536532011569e8602c47ecc0a3

I added this to b14 to go with the hw1 scout ability change.
