### ISSUE TITLE
Movement Speed While Being Repaired

### ISSUE THREAD

**Issue by cloaked2222** [HW-PlayersPatch/Development#256]
When ships are trying to repair the target is slowed down to this amount of it's max speed in Tuning.lua.
2.1: 0.65 (65%)
hw2 BC 99->64 (79 base->99 upgraded)
hw1 HC 115->75
2.3: 0.95 (95%, this was changed in 2.4)
hw2 BC 99->94
hw1 HC 115->109

Healing hw1 and hw2 cruisers with supports/repairs/colls is extremely strong in the late game, and vital in team games. Cruisers can kite with repair ships and last for a looong time, and there's little your opponent can do without taking heavy losses diving far into your defenses. This can make cruisers somewhat godly units, and make games drag on forever. One example would be the 2v2 me(H)/ghost(V)/tyguy(V)/robey(H) had a couple weeks back.

We could lower this value some, to make kiting cruisers a bit slower and easier to snipe.

Suggestion A: 0.8
hw2 BC 99->79
hw1 HC 115->92
Suggestion B: 0.85
hw2 BC 99->84
hw1 HC 115->98
Suggestion C: 0.9 and lower HC speed to 109 (a cruiser being repaired, should be slower than 99 speed)
hw2 BC 99->79
hw1 HC 109->98

**Comment by RoBeY4Gate** [comment]
I posted a lengthy response in discord, but overall I do agree with these specific changes.

**Comment by cloaked2222** [comment]
89ee568314b8b9f9c168b35d8d23c0186df36ecd
