### ISSUE TITLE
HW1 Ion Align to Target

### ISSUE THREAD

**Issue by cloaked2222** [HW-PlayersPatch/Development#265]
Fear: "They'll fire near the target but miss at a set angle, if you issue stop and attack again they right themselves"

I fixed this issue with the hiig cruiser sometime after v2.0 I believe. Do a diff on hiig cruiser .ship from 2.0 to now to find the fix.
There's an alignment angle that was set to say 15degrees that i lowered to say 5 degrees.
Also is this a current issue still? We increased all ion attack angles a couple builds ago.

**Comment by Novaras** [comment]
It is, also see https://github.com/HW-PlayersPatch/Development/issues/271 which may be related

It doesn't appear to be a weapon issue, as the entire ion cannon itself will be misaligned?

**Comment by cloaked2222** [comment]
Here was the fix for the hiig BC:
![image](https://user-images.githubusercontent.com/18016573/72027300-70d2fc00-324c-11ea-8791-9824bd7a700b.png)
The ship would be nose up or nose down 10degrees vs a target, and the nose of the ship would block one ion turret from firing...

Hiig Ion: NewShipType.descendPitch=35 (20 in hw2c)
Kus Ion: NewShipType.descendPitch=70

Holly hell, the kushan ion is set at a whopping 70degrees, lol. These both should come down to 5-10. Can't believe I didn't think of this before. I've noticed the hiig ions being bad for a long time, the kush ion is even worse...

**Comment by Novaras** [comment]
oh jeez, good find

can't believe this is easily fixable with a number change

**Comment by Novaras** [comment]
https://github.com/HW-PlayersPatch/Development/pull/276
