### ISSUE TITLE
Late game HW2 vs HW1

### ISSUE THREAD

**Issue by cloaked2222** [HW-PlayersPatch/Development#268]
Fear: "hgn late is obnoxious, specifically for hw1"

This is partially due to this: late game hw2 mostly builds frig+ and dock heals swarm, while hw1 may need to continue building all units if swarm battles are raging. Balance is screwed as long as hw2 has squads and hw1 doesn't.

Potential options:
A) Give hw1 2 more collectors
B) When dock-healing, make reviving a unit cost RU. Start with half as much as paying for a new unit, so for example a hw2 int revival would cost 45ru. If we can figure out how to do this. Note: this may make RU go below zero - as I doubt we can pausing docking if you have 0 ru.
C) Give all races the ability to build swarm units solo or in batches. This would be an option on the build menu, like what complex did.
D) Do a large re-work of research. Balance would be much better if hw1 had one hull/speed upgrade for each class like vaygr (fighters/corvs/frigs/caps/non-combat). This would allow for lower unit and tech costs, as some costs would be shifted to the new upgrade cost. Just before I started helping GBX with balance in June 2015, the unfortunate decision was made to combine hw2 lv1/2 research and not give any upgrades to hw1. =/ Also change hw1 tech tree to remove all frigate research pre-requisites from capital ship research in MP.
Etc

**Comment by Novaras** [comment]
I think A) is just a good start no matter what https://github.com/HW-PlayersPatch/Development/pull/270
B) is a very spicy idea, as expected people aren't happy with this concept
C) I personally really dislike this, you would now need to balance hw1 fighters both loose and in squads, the development overhead is high, and I vaguely expecting only one stance will realistically be used most of the time
D) this is a great idea, but will need a fleshed out prop

**Comment by SirBattlestar** [comment]
I belive this has alot to do with the pos hyper torp and torp frig in general are performing vs corvettes and fighers.
option B) should be implemented. there should be no free lunch, when it comes to fighters. As it stands today i feel its fair bc of the preasure hw1 can put out early. late game it becomes a problem.
