### ISSUE TITLE
HW2 Collector Repair Rate

### ISSUE THREAD

**Issue by cloaked2222** [HW-PlayersPatch/Development#269]
Fear: "hw2 coll repair is trash"

Its usually best to keep harvesting, until super late game when you've got a big 10-20k ru bank. Then pull colls to repair and win some key battles. I did a quick shitty non-accurate test, and looks like 6 supports heal a hw2 cruiser twice as fast as 6 repair colls. Its prolly fine for hw2 colls to match a repair corvette, given the lack of harvesting

**Comment by Novaras** [comment]
I'm fine with this, although this is one of these features which technically makes no *sense* in its current state, but I'm not very confident if the game needs it right now... HW2 capitals aren't particularly weaker than HW1, they are cheaper and come out faster, and get fire controls and whatnot

Repair is basically the only thing HW1 has going for it in the lategame... Evening the field here is so harsh

**Comment by cloaked2222** [comment]
HW2 repairing half as fast as a hw1 support frigate is prolly fine. Don't need to give hw2, hw1's super powers.

Also don't want to encourage people to pull all collectors to repair BC's/DD's for a all-in push that would overwhelm hw1... Similar to the crap that was going on when SC2 was released with SCV pulls...
