### ISSUE TITLE
Vaygr cruiser tricannon misses vs shipyards and carriers

### ISSUE THREAD

**Issue by Novaras** [HW-PlayersPatch/Development#271]
Vgr tricannon will miss with a high rate vs shipyards, and will also miss often against vgr carriers, although I expect it will also miss others.

Basically, tricannon should probably never miss anything bigger than a destroyer.

This behavior seems to be some kind of bug, as its not consistent and it quite hard to reproduce reliably in my experience. Poke ghostrider for a ghost story about missing 9 shots in a row against my shipyard a few days ago.

**Comment by cloaked2222** [comment]
In the balance window, spawn 1 vay bc vs 1 vay SY. The first trinity shot misses while the BC is still rotating to face the target. Figure out why this is, and you'll likely have your answer.

NewShipType..descendPitch = 10
Try making this 5, and see if it resolves the above test case. Might be more to the story though.

**Comment by SirBattlestar** [comment]
Should vay cruiser miss on destroyers at all? All other cruisers hits the target unless they are out of range right? And after the range nerf, and the clear dissadvage of haveing to face the target, hitting the dds should be garanteed in my opinion

**Comment by Novaras** [comment]
I'm having a ton of trouble trying to get this to trigger reliably. In testing I don't seem capable of missing...

**Comment by cloaked2222** [comment]
I just made descendPitch=10->5, like the Hiig BC.
e64ec513bf51bb11bc54bb5c3335326358866001

This should have been implemented in January.

This bug is rare/hard to reproduce, but this should definitely help and may fully resolve it.
