### ISSUE TITLE
Ions Over-performing vs Corvettes

### ISSUE THREAD

**Issue by cloaked2222** [HW-PlayersPatch/Development#275]
The following results look good. This is because ion frigates have a hard time rotating to face corvettes swarming around them:
15 Missile Vett Squads vs 10 Kushan Assault Frigates. Frigs won with 7 units left after 220 seconds.
15 Missile Vett Squads vs 20 Kushan Assault Frigates. Frigs won with 20 units left after 115 seconds.
15 Missile Vett Squads vs 10 Kushan Ion Frigates. Missiles won with 15 squads left after 309 seconds.
15 Missile Vett Squads vs 20 Kushan Ion Frigates. Frigs won with 12 units left after a whopping 735 seconds (over 12minutes).

However the following results suck, and its a scenario I hadn't tested before. Spawn the frigs as p2 and corvs as p1, click fight, then spawn P1 hw1 resource controllers and have your missile vettes force attack them.
20 Kushan Assault Frigates vs 15 Missile Vette Squads attacking a resourcing operation = 160 seconds for frigs to kill corvs
20 Kushan Ion Frigates vs 15 Missile Vette Squads attacking a resourcing operation = 160 seconds for frigs to kill corvs
Ions should not be killing corvs faster than assaults... Moving corvettes should be much harder for ions to hit.

A recent build increased the ion cone 6->12. Now that we know the proper way to fix their target alignment issue (descendPitch), we might want to return these to 6. Or we can also lower hiig/hw1 ion frig accuracy significantly vs corvettes to compensate, which is probably what we should do.

**Comment by Novaras** [comment]
Done here: https://github.com/HW-PlayersPatch/Development/pull/276
