### ISSUE TITLE
HW1 Assault Frigs vs Moving Frigs

### ISSUE THREAD

**Issue by cloaked2222** [HW-PlayersPatch/Development#292]
Per Fear, HW1 Assault frigates have a hard time hitting moving frigates.

This is due to having the 2nd lowest horizontal/vertical tracking speed in the game at 25/25.

The goal is to fix assault frigates vs moving frigs, while retaining their current balance balance vs moving interceptors and corvs (test pulsars/missiles/heavies).

I'd suggest making them 40/40 and lowering their penetration vs fighters/corvs.

**Comment by Novaras** [comment]
Don't think they need nerfing in any way: https://github.com/HW-PlayersPatch/Development/pull/300

**Comment by cloaked2222** [comment]
Since we didn't test actual issue after changing to 40/40... lol ...this issue may need to be re-opened.

I just tested in build 14: 2x Kus Ions vs 4x HW1 Assault Frigs, and 2 Kus Ions vs 4x Vay Assault Frigs.
Basically its possible to micro ur frigs left/right and dodge some shots from HW1 AND Vaygr Assault Frigs, just the same.
If your moving your frigs to the right, the enemy will fire shots farther to the right to lead their target using velocity prediction. But if you move left as the enemy is firing, some bullets will shoot into space where you were 'expected to go' and miss. This is basically ballistics in action as intended by GBX, and I suspect many other frig/capital guns will act the same (unless they have ballistics disabled...). Most shots do land even vs shuffle micro, so its not a huge deal. But the projectile speed of affected ships can go up some next build if needed.
