### ISSUE TITLE
Torpedo Frigate Range

### ISSUE THREAD

**Issue by cloaked2222** [HW-PlayersPatch/Development#315]
HMF have 3750 range. Hiig Ions have 4000 range. HW1 Ions have 4250 range. Torps have 4500 range.
HMF/Ions all have 165 speed. Torps have 176 speed. But HW2 can upgrade these speeds.

Torps have significantly more range and speed than any other frigate, which means if they are micro'ed perfectly they can kite and beat any frigate without a scratch. Generally if a frigate/capital ship has more range, it should have less speed. Otherwise it can infinitely kite, and become invincible. But I don't plan to lower them to 3750 to remove this entirely.

Instead I propose lowering their range to 4250 (-5%) to match the HW1 Ions. And yes they can still be micro'ed vs HW1 Ions as you can pull them as soon as the torp deploys. HW1 Ions have to stay in range for a while while their ion beam lines up, fires, and deals damage over a few seconds. And obviously you can still kite them vs HW2 frigates, it would just be a bit harder to do.

This way they can still kite all frigates, but it will be harder to do so. People are unlikely to kite perfectly, and there are certainly other counters to torpedo frigates, so they are not a god tier unit. Just a small nerf.

**Comment by Novaras** [comment]
https://github.com/HW-PlayersPatch/Development/pull/316
