### ISSUE TITLE
SP HW1 M4 Missing Dialogue and Cutscenes

### ISSUE THREAD

**Issue by cloaked2222** [HW-PlayersPatch/Development#320]
https://steamcommunity.com/app/244160/discussions/1/618458030658516067/

**Comment by Stuart1998** [comment]
I wasn't able to reproduce this and I can't find evidence of this being a normal bug at any point in the remaster based on several videos from different years on youtube. Closing.

**Comment by cloaked2222** [comment]
Someone else just posted this issue again: https://steamcommunity.com/workshop/filedetails/discussion/1190476337/1733214357975335317/?ctp=13#c3731827719866458807

Perhaps the issue only occurs sometimes.
