### ISSUE TITLE
HW1 Utility Health

### ISSUE THREAD

**Issue by cloaked2222** [HW-PlayersPatch/Development#343]
HW1 utility ships are quite fragile, and use the same armor as frigates. They might need a health bump. For reference HW1 ion frigates have 26k health, torps have 14k->19.6k health.

Unit | Current Health | Relatively closer to hw1c | Proposed
--- | --- | --- | ---
kus_cloakgenerator.ship | 9k | 11k | ~~15k~~17k
kus_gravwellgenerator.ship | 11k | 14k | 19k
kus_sensorarray.ship |  5.5k | 8k | ~~11k~~15k

Currently when a GW activates its ability, it loses half its health by the time its energy is nearly dry. Lets make sure this is still the case after this health buff.

Note: GWs at 11k allow 2 resource collectors to kami into them and kill them. This allows swarming players a way to kill GWs without frigs+. We would lose this hw1c counter, however honestly I've never seen anyone utilize this in a HWR game...

**Comment by Novaras** [comment]
i'd say 16/16/19 instead of 15/11/19

**Comment by cloaked2222** [comment]
How bout this:
![image](https://user-images.githubusercontent.com/18016573/82227826-48dc5f00-98f6-11ea-9899-a6d14200ca12.png)

**Comment by Novaras** [comment]
That seems pretty good to me yeah, 11k was quite a low target
