### ISSUE TITLE
Anti-Swarm Frigate Tuning

### ISSUE THREAD

**Issue by cloaked2222** [HW-PlayersPatch/Development#344]
Tune the matchups below to all be similar times to kill the swarm.

35 H Ints + 21 H Gunships vs:
- 3 Flak + 3 Torps
- 6 Vay assaults
- 3 Drone + 3 Kus assaults
- 3 drone + 3 Tai assaults

The hiig frigs are specialized, while the vay frig is a generalist. Currently I suspect the vay assault frig may significantly over-perform in the above test case. Drones might also be over-performing vs corvs in the above test case. Test to see, really this is just a hunch, could be a total non-issue.

**Comment by Novaras** [comment]
[swarm_kill_time.zip](https://github.com/HW-PlayersPatch/Development/files/4592137/swarm_kill_time.zip)

**Comment by cloaked2222** [comment]
I take it these are b14 results?

Ignoring test 1 results (don't care about un-upgraded tests). Here's test 2 times to kill:
Hiig: 106
Vay: 138 (kill fighters in ~60 seconds)
Kus: 155
Tai: 162
Don't know why I was thinking vay assault frigs were great vs corvs, lol... Vay results above actually look fine, since the vay assault frig is primarily anti-fighter. Looks like hw1 needs work.

Before we do any further testing, can we please resolve the 4 high/medium [balance-screen issues](https://github.com/HW-PlayersPatch/balance-screen/issues)?
