### ISSUE TITLE
Non BIG releases

### ISSUE THREAD

**Issue by mjhorvath** [HW-PlayersPatch/Development#361]
Could you please also upload releases that are not packaged in a BIG file? Thanks.

**Comment by cloaked2222** [comment]
Releases for Build 7 and up are all on GitHub.

Packaged .big releases: https://github.com/HW-PlayersPatch/File_Share/tree/master/Releases

Loose files: https://github.com/HW-PlayersPatch/Development/commits/master
Use GitHub Desktop or another git application to pull/download the files. You'll want to select the appropriate commit in the history such as "Build X Release". Note that build 7 was simply named "base files for 2.3", as we had just started using GitHub.
