### ISSUE TITLE
Vaygr heavy missile trail fix

### ISSUE THREAD

**Issue by VortiK** [HW-PlayersPatch/Development#395]
Hello, 

I've noticed that the Vaygr heavy missile engine trails are shorter in HWRM than in HW2C, it's possible to fix this by changing the `Data\missile\vgr_heavymissile\vgr_heavymissile.miss` file that is not overridden by the playerspatch mod yet.

without the fix : 

![image](https://user-images.githubusercontent.com/23299769/155182696-e072499b-b25b-43fd-8ad6-64db8e576ea1.png)

with the fix : 

![image](https://user-images.githubusercontent.com/23299769/155182263-dadb0dfc-7948-4241-a2dc-abb0c86c7879.png)

attached file to rename to .miss ofc : 

[vgr_heavymissile.miss.txt](https://github.com/HW-PlayersPatch/Development/files/8118580/vgr_heavymissile.miss.txt)

I've tested by simply droping the file in Data with overridebigfile parameter and it works file!

I found the fix in this mod : https://steamcommunity.com/sharedfiles/filedetails/?id=414917635

Would be nice if it could be integrated in the playerspatch mod thanks.

**Comment by cloaked2222** [comment]
VortiK - Gearbox intentionally made multiple art/fx changes for remastered to give remastered a new look. Some were even provided by Battlecry from the PDS mod for the 2.0 patch. Fear and I chatted about this and he prefers the new look. I dont have strong opinions either way, but short of doing a large art/fx overhaul to return to the classic effects, Id lean towards just leaving it as is for now.
