### ISSUE TITLE
CTD when transitioning between SP Missions

### ISSUE THREAD

**Issue by EliasHeydrich** [HW-PlayersPatch/Development#404]
Using an up-to-date **GoG** release of Homeworld Remastered and build14 of the Player's Patch, there are multiple, reproducable crashes to desktop when transitioning between missions. The game **c**rashes **t**o **d**esktop (CTD), showing an _Access Violation_ and no further details.
There is a workaround: After restarting the game, one can simply launch the (now unlocked) mission again and it loads without issue.

This happens, for example, while playing for the first time, when transitioning from HM1RM_M1 to HM1RM_M2. Other missions in both games are also affected. This is not an issue limited to my machine, as others have reported it as well.

![grafik](https://user-images.githubusercontent.com/45756647/215544583-5961addc-0b47-4aa2-a0ee-f5fb2a9848d3.png)

**Comment by cloaked2222** [comment]
@EliasHeydrich - See the [Troubleshooting Thread](https://steamcommunity.com/workshop/filedetails/discussion/1190476337/1733214357975335317/). HWR is not the most stable game and some intermittent crashes are typical while transitioning between campaign missions. This is an issue with the default game engine and it can occur with or without the patch.
