### ISSUE TITLE
SP HM1RM_M13 Junkyard Issues

### ISSUE THREAD

**Issue by EliasHeydrich** [HW-PlayersPatch/Development#405]
The following was observed on my last playthrough, using an up-to-date **GoG** release of Homeworld Remastered and build14 of the Player's Patch:

Under unknown conditions, the Junkyard Dog is unresponsive and simply does not act during the entire mission (making the mission very boring). It remained static for the entire mission until destroyed by my many capital vessels.
This **could** be related to other transition issues (see #404) I noticed, as the behavior could not be reproduced when starting the mission directly from the menu.

When the Junkyard Dog was functional and acting normally, it was noted that the captured vessels are spawned in Taidan colors, including the Empire Symbol. If possiblle, this should be changed as it neither makes sense lore-wise nor benefits the mission.

**Comment by cloaked2222** [comment]
@EliasHeydrich - Thanks for reporting this. I just added it to the campaign Discussion [here](https://steamcommunity.com/workshop/filedetails/discussion/1190476337/1621724915765581929), where most campaign issues are reported.

The Junkyard Dog sometimes has issues, another report is [here](https://steamcommunity.com/workshop/filedetails/discussion/1190476337/1621724915765581929/?ctp=5#c3051737278916799694). The issue with team colors for captured ships is common.

Note that these are issues with the default game. The homeworld 1 mission scripts were imported from homeworld classic into the remastered engine. Unfortunately they are a mess and sometimes do not execute properly. Fear would like to re-write them from scratch, haha.
