### ISSUE TITLE
SP: Reactive Scaling

### ISSUE THREAD

**Issue by cloaked2222** [HW-PlayersPatch/Development#41]
Goal: Reduce the variation in the AI reactive fleet size, by averaging the players starting fleet with the expected starting fleet size.

"@cloaked Does your patch in anyway address HW2 engine scaling (where the amount of the ships the enemy has is based on your own amount) in HW Remastered? Because it sort of sets the whole HW1 experience on its head, where instead of rewarding you for capturing many enemy ships with an easier game, you get penalized."

Cloaked: Everyone think's HWR's mission scaling is over-the-top compared to hw1c. Apparently hw1c was a pretty standard enemy fleet with not too much variance. Where-as HWR if you come in with nothing, enemy fleet is tiny, and if u come into mission with max unit caps, enemy fleet is huge.
Fear: yah
Cloaked: So i think i finally have a solution for this to reduce the enemy fleet size range from say 1-10, to more like 3-7. For a more 'consistent' mission feel, that doesn't punish players for doing well in the previous mission. (While still allowing ppl to crank up the difficulty of course)
Fear: wow thats perfect
Cloaked: =D

This is kinda huge, tones of ppl have been asking for this for years, with no 'real' fix. Yes you can set the difficulty slider in v2.3 to 0.5 to turn down reactive scaling - but then every mission is super easy...

The draft solution is in the next post, but needs your help!

Edit:
Also test m3 reactive fleet. Save game at end of m2, then go to m3. Then repeat but recycle all combat ships at end of m2. I'm interested to see how much more important your ships are vs your RU.

**Comment by cloaked2222** [comment]
In HWR's missions we have two things we can tweak: multiplierForExtraShips and multiplierForExtraRU. In v2.1 these are both always equal to 1x.

v2.3 adds a slider so you can set these from 0x to 2x. Current code:
> Data\leveldata\campaign\homeworldclassic\mission03\referencefleet.lua
> --Load expanded options
> dofilepath("data:scripts/playerspatch_util.lua")
> RefMissionDifficultyScale = GetMissionDifficultyScale()
> 
> multiplierForExtraShips = RefMissionDifficultyScale
> multiplierForExtraRU = RefMissionDifficultyScale

New code:
> Data\leveldata\campaign\homeworldclassic\mission03\referencefleet.lua
> --Load expanded options
> dofilepath("data:scripts/playerspatch_util.lua")
> RefMissionDifficultyScale = GetMissionDifficultyScale()
> 
>RefMissionDifficultyScale = RefMissionDifficultyScale * NormalizedScaling()
>
> multiplierForExtraShips = RefMissionDifficultyScale
> multiplierForExtraRU = RefMissionDifficultyScale

For this example lets pretend GetMissionDifficultyScale() = 1.0 (1x)
"HWR if you come in with nothing, enemy fleet is tiny, and if u come into mission with max unit caps, enemy fleet is huge."

What were going to do is check the players fleet upon starting the level, and compare that to the reference 'expected' fleet. If the players fleet is tiny, were going to make NormalizedScaling() = 1.5x-ish. So instead of spawning a tiny enemy fleet, a more modest enemy fleet will be spawned. Reverse applies if the players fleet is huge, were going to make NormalizedScaling() = 0.5x-ish.  So instead of spawning a huge enemy fleet, a bigger than normal fleet will be spawned.

I'd like you guys to help come up with a formula for NormalizedScaling() that makes sense. Using these 4 functions:
	print("** The total value of the reference fleets ships is "..GetReactiveFleetSizeInRU().."RUs")	
	print("** The reference fleet has  "..GetReactiveFleetExtraRU().." RU's in its initial allocation")
	print("** The total value of the players ships is "..GetActualPlayerFleetSizeInRU().. "RUs")
	print("** The Players persistant fleet has "..GetActualPlayerFleetExtraRU().." RU's on entering the level")

NormalizedScaling() will go in playerspatch_util.lua. It should work there, but if it don't you can test it in scar_util.lua instead where it should 100% work.

To test use -luatrace (i think) command line, and play HW1 Mission 3. 

Tweak your starting fleet here: HomeworldRM\Bin\Profiles\Profile1\Campaign\HOMEWORLDCLASSIC\persist2.lua

**Comment by Novaras** [comment]
as expected, the issue is a scope-related one... the variables we need to alter exist in `referencefleet.lua`, and are inaccessible otherwise... there's no point bringing in this file with a `dofilepath` as the file is just loaded from its clean state in some hardcoded function, namely: `SobGroup_LoadPersistantData`

this means we need to do our stuff inside 'referencefleet.lua' itself, however this file has no scope access to any of the functions we need... what would have to be done is creating our own function which can read the `Fleet` table and calculate the RUs represented by it, then use that number for our calculation

the calculation itself isn't any issue, im using:

~~~
-- normalize scaling between 1.5x and 0.5x, min is expected / 3, max is expected * 3
function NormalizeScaling(actualVal, referenceFleetVal)
	local min = referenceFleetVal / 3
	local max = referenceFleetVal * 3
	return ((0.5 - 1.5) * ((actualVal - min) / (max - min)) + 1.5)
end
~~~

i hope you know some solution, i dont know much about this stuff

**Comment by cloaked2222** [comment]
I have several tricks up my sleeve i can try. For example you can save values to a file and read them back elsewhere.

Ill stab at it later on. Formula looks good!

**Comment by Echo1707** [comment]
I'm playing the classic version that comes with the Gearbox bundle, and as a reference, starting mission 03 with 4 heavy corvettes, 5 repair corvettes, 6 salvage corvettes, 1 resource collector and 1 research ship, the enemy strenght is 4 assault frigs. The first cryo tray went down at 1:55 seconds, but keep in mind that in the mod:

**Assault Frigate**
Plasma launchers damage increased from 55-65 to 75-110

**Comment by Novaras** [comment]
the only way i can conceive of doing what we're after is to write to a file at the end of the previous mission so the data is available to be called in time for the reference fleet file load

**Comment by Novaras** [comment]
Hey, what's the status of this? @cloaked2222

**Comment by cloaked2222** [comment]
I'll tackle reactive scaling someday, maybe in the winter time.

**Comment by cloaked2222** [comment]
pie in the sky
