### ISSUE TITLE
SP: IF ONLY I WERE THIS RICH IN RL (aka: too many RUs in campaign)

### ISSUE THREAD

**Issue by Echo1707** [HW-PlayersPatch/Development#43]
HW1C didn't have autocollection, but it is present in the RM version. The autocollection rate in HW1RM M03 is 100%, but I don't know where this value is stored.

It's okay to have an autocollect in the HW2 campaign. but I'd rather not have it on HW1. There might be already way too many RUs in the remastered already.

**Comment by cloaked2222** [comment]
If hw1c for sure didnt have it, setting to 50% if possible may be desirable.

**Comment by cloaked2222** [comment]
Ideally RUs need to be adjusted on all hw1 mission levels. FYI some levels spawn more dust clouds when the player is struggling.

Setting auto-collect to say 50% if possible may be the quick fix.

**Comment by Echo1707** [comment]
I'm playing the classic version that comes with the Gearbox bundle and using the [Splendor mod](https://forums.gearboxsoftware.com/t/homeworld-splendor-mod/93167) on top of it, and there is no autocollect.

**Comment by Echo1707** [comment]
In addition to the edits above, there is also the fact that having autocollect at anything different than 100% (0% included) adds another variable to the equation of SP balancing: how much time is the average player going to spend on resourcing.

**Comment by cloaked2222** [comment]
Change the topic title. That's the real issue here "IF ONLY I WERE THIS RICH IN RL".

Remember that after lowering mission map RUs, there are new players that actually struggle to get by. So adding more spawnable dust clouds for said players may be a good idea. The worst thing would be for a new player to start a mission with nothing left in his fleet, not have enough ru on the map to beat the mission, and have to restart the game from several missions prior, to be able to progress.

**Comment by cloaked2222** [comment]
FYI, all the other key 2.205 campaign files are now here:
https://github.com/HW-PlayersPatch/2.3/blob/Cloaked/Resources/2.205%20Campaign%20Files.zip

**Comment by Echo1707** [comment]
It is possible to complete the missions very quickly (or at least, as fast as possible), autocollect at the end of the first two missions and still win: just as a reference, in M01 I made the bare minimum required to accomplish the mission (so no int research), retired all 7 scouts, harvested everything, and started M02 with 14 salvage corvettes; then in M02 I just salvaged the turanic raiders corvettes and had them kill the fighters.

Ah, have to switch off. Reminder for myself: bentusi exchange cost in classic, collectors harvesting faster, lowering tech, try difficulty 3.0 with quick quick missions, count assault frigs, search for the file that Gearbox used to tell what/how many ships/RUs devs are expecting and test if it works.

**Comment by cloaked2222** [comment]
Research   Costs | 2.205 | b8 | Mission First Available
-- | -- | -- | --
kus_fighterdrive | 0 | 500 |  
kus_fighterchassis | 200 | 800 |  
kus_defendersubsystems | 300 | 1000 |  
kus_plasmabomblauncher | 400 | 1000 |  
kus_cloakedfighter | 500 | 1100 |  
kus_corvettedrive | 300 | 1500 |  
kus_corvettechassis | 400 | 1200 |  
kus_heavycorvetteupgrade | 500 | 600 |  
kus_fasttrackingturrets | 600 | 800 |  
kus_minelayingtech | 700 | 1200 |  
kus_capitalshipdrive | 800 | 1300 |  
kus_capitalshipchassis | 900 | 1500 |  
kus_ioncannons | 1000 | 2000 |  
kus_dronetechnology | 1100 | 1300 |  
kus_supercapitalshipdrive | 1300 | 1700 |  
kus_superheavychassis | 1400 | 5000 |  
kus_guidedmissiles | 1900 | 3500 |  
kus_heavyguns | 3000 | 9000 |  
kus_sensorarray | 150 | 1000 |  
kus_proximitysensor | 300 | 500 |  
kus_gravitygenerator | 700 | 500 |  
kus_cloakgenerator | 700 | 800 |  
Total Research Costs | 17150 | 37800 |

**Comment by Echo1707** [comment]
M02: +20 (2112 ---> 2132) [there was a dust cloud with 750 RU which was further away than the asteroids. Reduced the dustcloud to 500 RU all 9 asteroids with 220 RU go up to 250 RU]

M04: +500 (OK) [8*225 + 10*900 ---> 8*250 + 10*930]

M04.5: lower priority compared to proper campaign

M05: +696 (1300-595 = 705) [84*223 + 24*80 ---> 84*231 + 24*81] {could have been 24*82, but I'm going with less resources to have less ships when the player encounters the swarmers}

M06: -594 (1000-1582 = -582) [22*100 ---> 22*73] {could have been 22*74, but I'm going with less resources to have less ships when the player encounters the swarmers; note for proper campaign balancing: maybe kamikaze asteroids could yeld less resources or standard asteroids could go to zero?}

M07 and M08: not reallly any need to change them for a few RUs. Unless we cut M06 and M07 RUs to something that forces the player to start those missions with so few ships that swarmers aren't a threat (as long as they have 1 drone frig and 2 support frig)

From M09 to M16: not really concerned for -2k RU in campaign, but I'll try to adjust them later. Got go go now.

**Comment by Echo1707** [comment]
I updated my comment above, please have a look :) https://github.com/HW-PlayersPatch/2.3/issues/43#issuecomment-412301243

**Comment by cloaked2222** [comment]
Rofl about Bentusi, ya the research cost from Bentusi should be a bit higher than normal then. Maybe 1.25x or so. Can you post the hw1c and HWR Bentusi research costs?

**Comment by Echo1707** [comment]
**HW1C**
M04, Ion Cannon Research: from 300 RUs to 500 RUs (depends on starting RUs?)
M06, Drone/Defense Field Technology: 500 RUs

**HW1RM**
M04, Ion Cannon Research: 500 RUs (2000 RUs in b9)
M06, Drone Technology: 500 RUs (1300 RUs in b9)

To put things into perspective:

_To be finished_
Reminder for self: force attack the cryotrais in M01 both classic and RM

**HW1C**
HW1RM M01: 750 starting RUs + 600 RUs = 1350 RUs
HW1RM M02:  RUs (+ 1350 RUs =  RUs total)
HW1RM M03:  RUs (+  RUs =  RUs total)
HW1RM M04:  RUs (+  RUs =  RUs total)

**HW1RM**
HW1RM M01: 750 starting RUs + 2250 RUs = 3000 RUs [NOT counting scouts retirement]
HW1RM M02: 8270 RUs (+ 3000 RUs = 11270 RUs total)
HW1RM M03: 4512.5 RUs (+ 11270 RUs = 15782.5 RUs total) [NOT counting assault frigs retirement]
HW1RM M04: 11300 RUs (+ 15782.5 RUs = 27082.5 RUs total)

**Comment by cloaked2222** [comment]
Depending on the mission dialog, I'd say make the research from the Bentusi cost the same or just a bit more:
Ions: 2000 or 2500
Drones: 1300 or 1600

**Comment by cloaked2222** [comment]
Bentusi research now costs the same as normally researching the items, however if you have super low RU your offered it at a discount.
Level RU was aligned well with HW1 research costs in build 10.
We may still get rich playing SP, but perhaps there are those that are barely getting by.

**Comment by cloaked2222** [comment]
People are still getting way to rich: https://steamcommunity.com/workshop/filedetails/discussion/1190476337/1621724915765581929/?ctp=4#c2273701484020702460

We need to determine how much RU each level had in hw1c, and update the level RU to be relatively similar.

**Comment by cloaked2222** [comment]
Pie in the sky. Good enough as is.
