### ISSUE TITLE
SP HW1 M3 capturable assault frigs

### ISSUE THREAD

**Issue by Echo1707** [HW-PlayersPatch/Development#70]
Assault frigs can be brought into the MS by salvettes, but they never get out of it; they just disappear (retired?).

In HW1C, the very first assault frigs gets instantly retired (you get some RUs out of it), while the next frigates get fully captured.

I'll see what I can find on `mission03.lua`.

**Comment by Echo1707** [comment]
I had a look at the file, but I don't understand anything :(

**Comment by cloaked2222** [comment]
In HWR do all frigs get retired, or just the first 2? I only tested 2, didn't try doing say all 5.

Haha, ya its a long script. You really gotta read and re-read these things a bunch to start to understand them. I've tweaked a few of these now, but its a lot of trail and error.

Did a search on "capture", and these lines look like they may be important. Try commenting out these lines by adding two dashes '--' in front of them:
> --make sure these enemy frigs don't get added to player fleet if/when captured
SobGroup_InactiveWhenCaptured("ImNotDeadYet", 1)
SobGroup_InactiveWhenCaptured("EnemyFrig01", 1)
SobGroup_InactiveWhenCaptured("EnemyFrig02", 1)

If that doesn't work, try commenting out these lines too:
> G_EnemyFrig01Captured = 0 --destroyed	
G_EnemyFrig02Captured = 0 --destroyed	
G_ImNotDeadYetCaptured = 0 --destroyed

**Comment by Echo1707** [comment]
Currently all frigs get retired.

Ah! So the magic word was "capture"... I searched "salvage".

Testing this is proving a bit problematic since now assault frigs do their job and kill my salvettes, but here are my results so far:
commenting out `SobGroup_InactiveWhenCaptured("ImNotDeadYet", 1)` made an assault frig freak out (salvettes latched onto it but couldn't move it; after being released, the frigate started turning but not moving);
commenting out `SobGroup_InactiveWhenCaptured("EnemyFrig01", 1)` seems to do what we want, just the first two frigs get retired while from the 3rd onward get captured.

**Comment by cloaked2222** [comment]
That's great.

I'd also test commenting out just this line, to see what happens:
SobGroup_InactiveWhenCaptured("EnemyFrig02", 1)

**Comment by Echo1707** [comment]
I updated my comment above with what I did so far. Seems like only commenting those lines isn't enough to replicate 100% what happens in classic :/
Depending on which frigates you capture first or kill, you could end up killing 1 frig (the one at 50% health) and capturing 5 of 5 salvaged frigs (all the others at 100% health).

**Comment by cloaked2222** [comment]
That sucks. Was hoping this would be an easy fix. The 5/6 option would be great, but the first frig needs to not be captured or its not gonna make sense. =/

This may require more serious mission scripting skills. Feel free to close this issue if you'd like.

**Comment by Stuart1998** [comment]
Fixed in ecc9977.

**Comment by cloaked2222** [comment]
The first frigate is torn down for research. Then a flip prolly gets thrown, to allow other frigs to be captured. Likely this switch is thrown after a 2nd frigate is being brought in for salvage. Hence usually 2 frigs aren't captured.

Knowing this is likely the problem, we may be able to fix it so all but 1 frig can be captured.
