### ISSUE TITLE
SP: Mission Difficulty Adjusters

### ISSUE THREAD

**Issue by cloaked2222** [HW-PlayersPatch/Development#77]
Would be nice to have two ways to adjust mission difficulty:
1. Mission Difficulty Scale
- Same as before.
- Mainly increases or decreases the size of the enemy fleet that is spawned, based on the size of your fleet.
2. Mission AI Attack Damage Scale
- Some people want to up the difficulty without spawning a ton of ships! This also is a flat difficulty adjuster, rather than being dependent on your starting fleet.
- 100-200, in increments of 25
- Looks like we would need to grant this research in each mission .lua file. In the onint section of code, grant WeaponDamageUpgrade125-200.

**Comment by Novaras** [comment]
Do you have a strategy to acheive this? Research granting in `.lua` files?

**Comment by cloaked2222** [comment]
I did this for MP/skirmish AI already, would use same method for SP. I want to tackle reactive scaling first though.
