### ISSUE TITLE
SP Campaign Bugs

### ISSUE THREAD

**Issue by cloaked2222** [HW-PlayersPatch/Development#80]
There's hundreds of other campaign bugs that don't have their own issue on GitHub. You can find many in these threads: 
1. Campaign Discussion thread:
https://steamcommunity.com/workshop/filedetails/discussion/1190476337/1621724915765581929/
2. Bug Reports thread:
https://steamcommunity.com/workshop/filedetails/discussion/1190476337/1733214357975335317/
3. Lots of threads on Gearbox and Steam forums

If you'd like to fix one of these bugs, just make an issue for it.

**Comment by Echo1707** [comment]
I don't know if it is a bug or if it is intended (and if it is, it's not like hw1c), but ships spawns in passive at the start of a mission, regardless of their default ROEs (that is, the starting ships are in passive, but every built ship in-mission spawns in defensive). In the classic version, ships in parade didn't chase off enemies, but they turned to shoot them and swung up/down/left/right around their given point in parade (thus trying to evade some incoming fire).

**Comment by cloaked2222** [comment]
HWR really could use a 4th ROE between passive and defensive... So ships stay in parade but defend themselves.

If we make all ships start in defensive (if possible), will that have any negative consequences? For example, in mission 3 units might start attacking the assault frigs on their own as they undock - which isn't desirable.

**Comment by cloaked2222** [comment]
HW2 M3, echo found this "All my ints/bombers can dock just fine, but my corvettes for some reason won't."
![thumbnail_homeworldrm 2018-08-15 20-12-21-60](https://user-images.githubusercontent.com/18016573/44242362-41bf7480-a197-11e8-951f-7a0cbbc178fd.png)

Echo, if this was caused by b8, plz test in b9 to confirm its resolved.

**Comment by cloaked2222** [comment]
@Echo1707 - I just noticed this was posted 2 days after build 8's release:
HW1 M9: https://steamcommunity.com/app/244160/discussions/0/617330406656722299/

Can you look into this when you get a chance.

**Comment by Echo1707** [comment]
> If we make all ships start in defensive (if possible), will that have any negative consequences? For example, in mission 3 that possibly could cause units to start attacking the assault frigs on their own as they undock - which isn't desirable.

I don't think this will happen (please see the video I linked in this comment https://github.com/HW-PlayersPatch/2.3/issues/43#issuecomment-412301243 at 21:16), however it has to be tested ;)

> Posting these from Echo's email:
> 
> HW1 M05 (but applies to other missions as well): all/most tai ships (resource collectors being a known exception) can't be immediately retired.
Echo, plz confirm this was possible in hw1c and post the results here

Tested and checked here (at 06:40; it was some time since I played that mission, so I'm being a bit clumsy here): https://vimeo.com/285692467 

It's fair to have it disabled for MP and HW2 campaign, since ships sizes greatily differ from hiigaran and vaygr (think about retiring a Vaygr BC in an Hiigaran SY), however in HW1 campaing this makes total sense (HW1 ships and hangars have about the same sizes between Kushan and Taiidan, and even the Turanic ion cannon frigate fits in the MS frigate hangar).

> HW2 M3 All my ints/bombers can dock just fine, but my corvettes for some reason won't.
> 
> Echo, if this was caused by b8, plz test in b9 to confirm its resolved.

Video (my pc survived the filming): https://vimeo.com/285901835

> @Echo1707 - I just noticed this was posted 2 days after build 8's release:
HW1 M9: https://steamcommunity.com/app/244160/discussions/0/617330406656722299/
> 
> Can you look into this when you get a chance.

I couldn't replicate the issue :(

**Comment by cloaked2222** [comment]
I would say it prolly makes sense to allow all captured/salvaged ships to be immediately retired in SP and MP - except hw2 cruisers and hw1 cruisers in MP. I just don't know if there was a reason why Relic did this, and I hate to break things. This could potentially be done with lots of testing. Same goes for defensive stance, would need thorough testing.

HW2 M3 - wow that's weird. Maybe something is going on in the mission script, to prevent corvs from docking at first. They appear to dock fine after you select fighters though...

**Comment by Echo1707** [comment]
HW1C: it's impossible to force-attack the cryotrais in M01
HW1RM: ...

![homeworldrm 2018-08-21 19-56-35-12](https://user-images.githubusercontent.com/39770560/44420154-7f4c4500-a57d-11e8-9e23-aa8d97dce93b.png)
![homeworldrm 2018-08-21 19-55-07-63](https://user-images.githubusercontent.com/39770560/44420158-82473580-a57d-11e8-97ca-ad43832ef6bc.png)
![homeworldrm 2018-08-21 19-57-01-93](https://user-images.githubusercontent.com/39770560/44420163-8410f900-a57d-11e8-9d0c-fa7c1123d3e9.png)

What did you expect? :sweat_smile:
