### ISSUE TITLE
MP: Balance Ideas

### ISSUE THREAD

**Issue by cloaked2222** [HW-PlayersPatch/Development#83]
Parking lot for general balance ideas and discussions. I'll keep the OP updated.

Putting some potential build 11 stuff here.
### All Races
Test full int+pulsar vs full AC+missiles. The sphereburst may make vay favored.

### Kushan/Taiidan
-Test Missile DD in -balance (Also check its hyp costs, as its the one unit u can jump home to deny harassment)

**Comment by Novaras** [comment]
Grabbag issue, unused.

Closing!
